name: VoidTeleport
version: '1.0.1'
main: me.seetch.voidTeleport.VoidTeleport
api-version: '1.20'
author: seetch
website: https://github.com/6mine/VoidTeleport

commands:
  voidteleport:
    usage: /voidteleport reload
    permission: voidteleport.*